SETTINGS_STATE_DISPLAY:
	db " Implication Station         ",__DATE__," "
	db "                                        "
	db " Settings                         Stats "
	db "                                        "
	db " [Name] Sort By                 SD Card "
	db " [ On ] Help Text                       "
	db "                          Size:     4GB "
	db " [Rebuild Library]        Free:   3.2GB "
	db "                                        "
	db " [Clear Favourites]                     "
	db "                                Library "
	db "                         Files:     327 "
	db "                         Built:23/09/08 "
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
	db "Press F10 to save and exit              "
	db "Press Esc to exit without saving        "
.END:
	nop
