BROWSE_STATE_DISPLAY:
	db " Implication Station          ",__DATE__
	db "  ../                                   "
	db "  Action/                               "
	db "> Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "  Bruce Lee's Kung Fu                   "
	db "                          F1/Settings   "
	db "                          F2/Search     "
	db "                          F3/Favourite  "
	db " /Games                   [Page   1/3  ]"
.END:
	nop
