SPLASH_STATE_DISPLAY:
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
	db "          Implication Station           "
	db "                                        "
	db "          MSX - 32kb Multi-Cart         "
	db "          ISMSX-322040                  "
	db "                                        "
	db "          Version ",VersionString,"                   "
	db "          Updated ",__DATE__,"            "
	db "                                        "
	db "          By Yassir Al-Refaie           "
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
	db "                                        "
.END:
	nop
